### ISSUE TITLE
Switch Date from Hyperbolic to Exponential Decline

### ISSUE THREAD

**Issue by dhickman81** [petbox-dev/dca#11]
Hi David,

Is it possible to retrieve the date at which the Modified Hyperbolic Decline model transitions into an exponential decline?

**Comment by dsfulf** [comment]
Yes, the hyperbolic models are implemented as a generalized multi-segment hyperbolic (of any number of segments). The MH and THM are mostly just ways to define what those segments are. After creation of the class instances, you can extract the segment parameters. The order is `start time, qi, Di (nominal), b, cumulative production at start`. You don't have to remember this order, and can use the attributes `T_IDX, Q_IDX, D_IDX, B_IDX, N_IDX` respectively.

![image](https://user-images.githubusercontent.com/8421927/112067401-ff702800-8b35-11eb-8e3f-f8c242487bb6.png)

**Comment by dhickman81** [comment]
Thanks David. This was very helpful!
