### ISSUE TITLE
Overflow Warning Encountered in Power

### ISSUE THREAD

**Issue by dhickman81** [petbox-dev/dca#13]
Hi David, 
I'm encountering an overflow warning when passing a value for bi that is small but not exactly zero 

![image](https://user-images.githubusercontent.com/36851406/114771527-4797fa00-9d32-11eb-8e0f-5b5722ea1410.png)

The fit.best_values were calculate by passing the dca.MH function to  [LMFIT](https://lmfit.github.io/lmfit-py/). 

Here are the details on the curve fit 

![image](https://user-images.githubusercontent.com/36851406/114772095-048a5680-9d33-11eb-88b2-87bde656b2f4.png)

It appears dca.MH is using the hyperbolic equation since b != 0, but in this instance b is very small so perhaps it should use the exponential decline instead. Normally I would just set bi = 0 and be done with it, but in this problem, bi can take on any value between 0 and 2 during the curve fit. Any suggestions?

**Comment by dsfulf** [comment]
The hyperbolic rate function reduces to the exponential form if b < 1e-10, but perhaps this should be increased a few orders of magnitude. Let me do some testing to find a good value.

**Comment by dsfulf** [comment]
Addressed in #10.

**Comment by dhickman81** [comment]
David,

Do I simply run a pip install petbox-dca --upgrade from my terminal or is there some other step I need to perform to bring in your changes?

Thanks,
David Hickman

________________________________

**Comment by dsfulf** [comment]
I need to publish to pypi first. I will do that in the next few days. Otherwise, you can install from master here.

**Comment by dsfulf** [comment]
@dhickman81 This is now on pypi. You can run the following:

`pip install --upgrade petbox-dca`
