### ISSUE TITLE
Which python module is "data"?

### ISSUE THREAD

**Issue by securitybryan** [petbox-dev/dca#16]
Hello David,

Great work here.  Love the way this is designed.

I am puzzled by the [example code](https://petbox-dca.readthedocs.io/en/latest/examples.html#detailed-usage-examples) which imports data types from data.  

`from data import rate as data_q, time as data_t`

Which library is that meant to be?

**Comment by dsfulf** [comment]
That’s in the /test/ directory. The code for the examples is in there as well, which is why that line you reference can find the namespace `data` in `data.py`

**Comment by securitybryan** [comment]
Thank you David.  I missed the reference link.  I'll check that out.

**Comment by dsfulf** [comment]
Happy to help!
