### ISSUE TITLE
Setting Upper Bounds on b for MH Model

### ISSUE THREAD

**Issue by dhickman81** [petbox-dev/dca#9]
Hi David,
Is it possible to relax the upper bound of 2.0 on the b parameter in the Modified Hyperbolic Decline model?

**Comment by dsfulf** [comment]
We can... but it’s there to disallow unrealistic forecasts. Can I ask why one would ever want to do this?

**Comment by dhickman81** [comment]
While we rarely see wells that exhibit/justify such a high b-factor, we do get b>=2 directly from ARIES and ComboCurve exports.  In order to replicate these forecasts, we would need to be able to calculate with a higher b regardless of how optimistic the "seller" curves are. 

I appreciate the quick response. No need to change for us at this time.  We can simply flag those forecasts that are using large b values and deal with them if they materialize on future deals.

**Comment by dsfulf** [comment]
OK, that sounds reasonable to me. I've pushed an update that allows passing a new optional keyword argument, `validate_params: Iterable[bool]`, which will toggle the validation of each parameter. Please pull this from the `develop` branch and ensure this works for you, and I will then merge to `master` and publish to `pypi`.

![image](https://user-images.githubusercontent.com/8421927/109061423-43454e00-76ac-11eb-942a-558b98bc076a.png)


Commit: 1c5ac4ca7553fda91d0f9bf176d899cad072749e
